### PR TITLE
.NET Fringe 2017 website

### PR DESCRIPTION
**Pull request by Aaronontheweb**
Still have some work to do on styling changes, but otherwise here good to go.

FYI: switched over to Jekyll and GH pages.

### CODE REVIEW

**Comment by SeanKilleen** [comment]
This PR is for the 2017 site. Some notes below:

## Remaining Work Before Merge
* [ ] Still need actual links for the CFP & Tickets. Right now both point to `todo.com`.
* [ ] The `_config.yml` file needs to have the URL updated so that it no longer points to localhost and points instead to the actual site's URL.
* [ ] Prior to accepting the PR, we might want to make sure that GH Pages doesn't expect the entire site to live in the `docs` folder, [per this Github link](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch). I think we should be fine, but want someone to give it a second look with less tired eyes. 

## Overview of updates in this PR
* A decision to pick a complimentary color to the blue (a mint green in this case)
* The docs pages have also been re-styled (not linked to yet because their content is older)
* The styles are now done using `.scss`
* Structure site pieces are broken up into Jekyll includes (nav, footer, etc.)
* Docs styles have been updated too -- it's all the same system now
* Some older stylings (e.g. `clearfix`) have been removed
* A `readme` was added to explain how to build the site

We're still eyeing [some other issues & enhancements](https://github.com/killeencode/dotnetfringe.github.io/issues) as well.

**Comment by SeanKilleen** [comment]
@Aaronontheweb also, it's the 2017 web site. Your PR title is so last year.

**Comment by SeanKilleen** [comment]
Other high-level updates that were made:

* A decision to pick a complimentary color to the blue (a mint green in this case)
* The docs pages have also been re-styled
* The styles are now done using `.scss`
* Structure site pieces are broken up into Jekyll includes (nav, footer, etc.)
* Docs styles have been updated too -- it's all the same system now
* Some older stylings (e.g. `clearfix`) have been removed
* A `readme` was added to explain how to build the site

We're still eyeing [some other issues & enhancements](https://github.com/killeencode/dotnetfringe.github.io/issues) as well.

**Comment by SeanKilleen** [comment]
A note: prior to accepting the PR, we might want to make sure that GH Pages doesn't expect the entire site to live in the `docs` folder, [per this Github link](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch).

I think we should be fine, but want to give it a second look with less tired eyes.

**Comment by Aaronontheweb** [comment]
@SeanKilleen yeah, still waiting on the other folks in charge of CFP and ticket sales to get their stuff setup... and my bad on the PR title

**Pull request closed without merging**
