### PR TITLE
Use web-optimized thumbnails in gallery to improve performance

### LINKED ISSUE #36: Reduce burden caused by images
Hi all,

Love the new site, and very excited to attend again this year! 

I noticed that all of the pictures in the gallery grid are roughly 400+ KB each. I figure we can knock the load time down quite a bit if we serve up thumbnails for the grid and only load the larger image when it needs to come down.

I'll submit a PR for it, but let me know if it's something you're not interested in doing for some reason.

Thanks again for putting this together!

### PR DESCRIPTION
**Pull request by SeanKilleen**
This resolves #36. 

Figured we we could add some thumbnails and make the gallery a little speedier.

### CODE REVIEW

**Comment by SeanKilleen** [comment]
I'm missing something about how the responsive images fit the grid. I cut them down to what I thought were the dimensions that they actually showed up in, only to have them look a lot smaller (CSS clearly isn't my strong suit).

I'll keep digging.

**Comment by thoward** [comment]
Thanks for the help Sean! This was not meant to be final (in fact we haven't even announced the new site/conference yet... how did you find it?!?). The image loading/gallery is verrrrrry slow for some reason. I'm not sure if that's the JS code, the size of the images, or the encoding of the JPGs (they were cut down from 5-7MB sized files by convert, which doesn't always encode so well). 

Anyhow, we definitely need a better experience for that before we publicize this and start getting real traffic. I'll open some issue about some other remaining work to be done on the site.

**Comment by SeanKilleen** [comment]
@thoward I think the site was slow because of the images. Huge difference for me locally when opening it up after these changes.

I found the site via @lenadroid's errant tweet (right place / right time I guess as it's since been deleted :smile: )

Happy to help with other remaining work -- I think this PR is good to go now, have a look when you get a chance and merge if it feels right. 

Also happy to squash if you don't want a bunch of commits all over the place.

**Comment by adron-orange** [comment]
Thanks for the notice @SeanKilleen. I'll take a gander at getting speedier images in there too, since I've got all the originals and some (newb) Photoshop chops I'll slim them up a bit more.  :)

@thoward I'll sync with you a bit later today and show you some of the other cool spastic images is shown you earlier.

Cheers all, thx!

Oh, and @SeanKilleen if you have any suggestions on image reductio magic I'm all ears. I just scale and minimize via photoshop usually.

**Comment by SeanKilleen** [comment]
@adron-orange honestly, for this one I just used Paint.NET, maintained the aspect ratio, and scaled down to where it was appropriate (ended up settling on 500px, which seems to fit the grid well for large screens and smaller alike). The responsive image CSS class that's in place does the rest.

I think they're reasonably squished -- went from ~400k --> ~40k, shaved about 7 MB worth of page load off in total.

Once this PR is merged, should be easy enough to add to the gallery and add the thumbnails as well.

**Comment by thoward** [comment]
This looks good to me. I'll go ahead and merge. 

That said, I think the JS library we're using for the gallery is part of the problem. I was going to move over to Photoswipe: http://photoswipe.com/documentation/getting-started.html .. if someone wants to take that one, it's pretty straightforward. You can just copy/paste from that Getting started guide. 

Let's do that in a different PR though. Merging now.

**Comment by thoward** [comment]
Actually, looks like this PR is more than sufficient for performance needs. Dont' bother with Photoswipe unless we start finding problems with mobile experience or other platform issues.

**Comment by SeanKilleen** [comment]
Sweet! Glad it had that much of an effect overall. Party on. :tada:

**Comment by adron-orange** [comment]
@SeanKilleen @thoward just checked too... looks good and is faster in Safari/Edge/Chrome for me too.

**Pull request merged**
