### PR TITLE
Suggested new speaker format

### PR DESCRIPTION
**Pull request by synhershko**
@glennblock @thoward what do you thing?

Few tweaks still needed but I think we can move ahead and apply this to all

Now speaker name is fully visible and we can provide more than one social link

### CODE REVIEW

**Comment by synhershko** [comment]
I'm taking this as a yes :)

Will go ahead and apply this change to the rest and merge by tomorrow

**Comment by glennblock** [comment]
I will look at it a little later

**Comment by glennblock** [comment]
What am I supposed to be seeing here? Blue circles for each link?

**Comment by glennblock** [comment]
I am not a fan of the circles approach. I have to hover on the circles and then look down to the address bar to see what it is. It is less obvious than what we have now.

The main issue with what we have now is it is inconsistent in that some have full names. I would change that, i.e. make Josh Van Eikeren, "@joshvaneikeren" and point to his linked in. We only have a few of those anomalies.

**Comment by synhershko** [comment]
The circles should have Twitter or Github logos on them, can't you see that?

I only applied this style to the first line of speakers. I put the full name instead of just a handle on purpose, I think that makes more sense

**Comment by glennblock** [comment]
Nope I don't see that. Are the images all included in the PR?

**Comment by glennblock** [comment]
Why does full name instead of handle make sense? Based on what?

**Comment by synhershko** [comment]
This is using font-awesome. I think you need to edit the HTML to have `https://` instead of just '//' in the link meta when viewing locally

Show me one conference that shows social handles instead of full names for speakers. I think speakers need to be represented with their full name, with links to social presence.

**Comment by glennblock** [comment]
@synhershko I'll try that out. 

As to whether or not other conferences do it or not, that doesn't mean we can't do it. I agree using handles is different, but I don't see different as wrong. Our whole event is about being different ;-)

**Comment by synhershko** [comment]
I believe most speakers will prefer their name up on the website as opposed to a handle that sometimes doesn't tell much, and often is different between sites. I know I do. And since we are putting links to more handles per speaker, why keep the handle in text and not put their name in now?

**Comment by glennblock** [comment]
Itamar, you send a PR with a suggested changed to the layout and I gave you feedback. This is not arguing, this is giving my thoughts on the suggestion. Saying you are going to just go ahead anyway and make the change is not OK with me. We don't operate like that. We work as a team. Please be respectful.

This is not an essential change. Please wait for others to weigh in and do not go ahead an merge until others respond.

Moving on..

I can see the images now. The circles are smaller less "in your face" and now actually icons. That does look much better. What I saw before had much larger circles. 

I don't have any problem with the proposal, but I'd like to hear what others think.

Here's an image so everyone can weigh in on the change.

screen shot 2015-03-22 at 11 35 30 am

**Comment by glennblock** [comment]
So in summary: :+1:  from me.

**Comment by glennblock** [comment]
What Font is being used for the names? Is that the way they should look or is it a different font and I am just not pulling in the right font locally?

**Comment by glennblock** [comment]
Updated image with the correct fonts.

screen shot 2015-03-22 at 11 41 17 am

**Comment by synhershko** [comment]
Fonts: that's again a missing HTTPS. I see you got it fixed now.

Some minor tweaks to those circles left (padding for the Twitter one), but I believe its way more respectful to all speakers this way. We are not showing bios, so at least lets have their names listed.

**Comment by glennblock** [comment]
@synhershko Yep. Any problem with just fixing that in the PR? It would make it easier for us to pull down and see it correctly without having to edit. I like it now much better. Thanks for the effort.

**Comment by glennblock** [comment]
@Haacked @thoward @IrisClasson @Adron can you guys weigh in on the screenshot above / give your thoughts on the change. Don't bother reading the rest of the comments.

**Comment by synhershko** [comment]
Fixing what? the HTTPS needs to be like that (problems are just when viewing locally), and the positioning of the icon I should be able to fix, yeah

Still need to apply this to the rest of the speakers anyway

**Comment by glennblock** [comment]
@synhershko I mean can you update the stylesheet in the link tags to use the full URI for the stylesheet so that when we pull we see it correctly without having to edit?

**Comment by synhershko** [comment]
I can do this, but like I said, the `//` stuff is intentional

**Comment by glennblock** [comment]
What benefit is having // over HTTPS in the live version?

**Comment by synhershko** [comment]
not sure tbh, it was like that when I went to edit. I think its a way to support moving between http/https, not sure. @thoward ?

**Comment by glennblock** [comment]
I see. OK. Leave it as is then.

**Comment by glennblock** [comment]
Folks, please weigh in. If Itamar doesn't hear back in a few hours, this will be merged.

**Comment by glennblock** [comment]
I'll be sending a PR with @synhershko's changes and the style applied for the rest of the speakers.

**Pull request closed without merging**
