### PR TITLE
Minor change.

### PR DESCRIPTION
**Pull request by Adron**
I made one last change. Flipping it to you pre-confirmation of dates.

That cool by you Troy?

### CODE REVIEW

**Comment by synhershko** [comment]
Mid is too broad?

**Comment by Adron** [comment]
Dates are still at the whim of venues. This removes anything that might be wrong a second time. Just thinking if we get bit by the date/time issue with venues again we aren't tied to something this time. Reduces the changes we have to make between now and upon announcement.

...and June is fine by me, just putting an option for @thoward in case it looks like we'll have to push past June or we can pull it off in May.

**Comment by thoward** [comment]
Let's just say "Summer 2016" (mid is just kind of weird phrasing).

**Comment by synhershko** [comment]
Done

**Pull request merged**
